/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package universitymanagementsystem;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     * 
     */
    private List<String> roles;
    public LoginGUI() {
        
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        loadRolesFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pwdTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Login Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Role");

        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(67, 67, 67)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameTF)
                            .addComponent(jComboBox1, 0, 137, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pwdTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   String id,pw,role; 
   boolean foundMatch = false;
   try{

    Connection con = (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/universityDB;create=true","root","root");
    Statement st;
    ResultSet rs ;   
    st = con.createStatement();
    rs = st.executeQuery("select * from roles");
    id = userNameTF.getText();
    pw =  pwdTF.getText();
    role = (String) jComboBox1.getSelectedItem();
    
    
         char[] passwordChars = pwdTF.getPassword();
        String password = new String(passwordChars);
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter id.");
            return; // Exit the method if the password validation fails     
        } 
       
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a password.");
            return; // Exit the method if the password validation fails
        }
        
        
    while(rs.next())
        {
             if(rs.getString(1).equals(id)&& rs.getString(2).equals(pw) && rs.getString(3).equals(role))
             {
              foundMatch = true;   
              if(role.equals("superadmin")){
              //System.out.println("I am in superadmin Dashboard ");
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              SuperAdminGUI s_adm_dash = new SuperAdminGUI();
              s_adm_dash.setVisible(true);
              setVisible(false);
              }
              
              if(role.equals("admin")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              AdminGUI adm_dash1 = new AdminGUI();
              adm_dash1.setVisible(true);
              setVisible(false);
              }   
              if(role.equals("dean")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              DeanGUI d_dash = new DeanGUI();
              d_dash.setVisible(true);
              setVisible(false);
              }
              
              if(role.equals("hod")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              HodGUI h_dash = new HodGUI();
              h_dash.setVisible(true);
              setVisible(false);
              }
              
              if(role.equals("faculty")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              FacultyGUI ff_dash = new FacultyGUI();
              ff_dash.setVisible(true);
              setVisible(false);
              }
              
              if(role.equals("student")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              StudentGUI ss_dash = new StudentGUI();
              ss_dash.setVisible(true);
              setVisible(false);
              }
              
              if(role.equals("guestteacher")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              GuestTeacherGUI gt_dash = new GuestTeacherGUI();
              gt_dash.setVisible(true);
              setVisible(false);
              }
                            
              if(role.equals("user")){
              userNameTF.setText("");
              pwdTF.setText("");
              JOptionPane.showMessageDialog(null,role+" Login Successfully");
           
              UserGUI u_dash = new UserGUI();
              u_dash.setVisible(true);
              setVisible(false);
              }              
              
             }
       }   
                 
        if (!foundMatch) {
            JOptionPane.showMessageDialog(null,"Invalid user name or Password\nTry again");
              userNameTF.setText("");
              pwdTF.setText("");
        }
    }catch(Exception se){}    
    }//GEN-LAST:event_jButton1ActionPerformed

     private void loadRolesFromDatabase() {
    // Replace with your own database connection details
    String url = "jdbc:derby://localhost:1527/universityDB;create=true";
    String username = "root";
    String password = "root";

    try {
        // Establish a database connection
        Connection connection = DriverManager.getConnection(url,username,password);

        // Create a statement
        Statement statement = connection.createStatement();

        // Execute a query to retrieve role data from the database
        String query = "SELECT role_name FROM roles";
        ResultSet resultSet = statement.executeQuery(query);

        // Populate the roles list and combo box
        roles = new ArrayList<>();
        while (resultSet.next()) {
            String role = resultSet.getString("role_name");
            roles.add(role);
        }

        // Add roles to the combo box
        for (String role : roles) {
            jComboBox1.addItem(role);
        }

        // Close the database resources
        resultSet.close();
        statement.close();
        connection.close();

    } catch (SQLException e) {
        e.printStackTrace();
        // Handle any errors that occur during database connection or query execution
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pwdTF;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
